# This workflow will run tests using node and uploads coverage report

name: fresource

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: ~/.yarn
          key: dependency-cache
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: yarn
      - run: yarn test
      - uses: actions/upload-artifact@v2
        with:
          name: test-artifacts
          path: ./coverage # upload coverage report for report-coverage job

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: ~/.yarn
          key: dependency-cache
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: yarn
      - run: yarn build
      - uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: ./dist # upload build artifacts for coverage job


  report-coverage:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: ~/.yarn
          key: dependency-cache
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - uses: actions/download-artifact@v2
        with:
          name: test-artifacts
          path: ./coverage # download coverage report from test job
      - run: yarn
      - run: yarn codecov
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  
